package co.edu.uco.rapizzas.crosscuting.messagescatalog;

import co.edu.uco.rapizzas.crosscuting.helper.TextHelper;

public enum MessagesEnum {
	
	USER_ERROR_SQL_CONNECTION_IS_EMPTY("Conexión contra la fuente de información deseada vacía", "La conexión requerida para llevar a cabo la operación contra la fuente de información deseada esta vacía. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_IS_EMPTY("Conexión contra la fuente de información deseada nula", "La conexión requerida para llevar a cabo la operación contra la base de datos llegó nula." ),
	USER_ERROR_SQL_CONNECTION_IS_CLOSED("Conexión contra la fuente de información deseada cerrada", "La conexión requerida para llevar a cabo la operación contra la fuente de información deseada esta cerrada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_IS_CLOSED("Conexión contra la fuente de información deseada cerrada", "La conexión requerida para llevar a cabo la operación contra la base de datos llegó cerrada." ),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_CONNECTION_STATUS("Problema inesperado validando el estado de la conexión contra la fuente de datos deseada ", "Se ha presentado un problema inesperado tratando de validar el estado de la conexión requerida para llevar a cabo la operación contra la fuente de información deseada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_CONNECTION_STATUS("Error inesperado validando si la conexión contra la base de datos estaba abierta", "Se presento un error de tipo SQLException al validar si la conexión contra base de datos estaba o no abierta." ),
	USER_ERROR_TRANSACTION_IS_NOT_STARTED("Manejo de operaciones frente a la fuente de información deseada no ha sido iniciado", "No se ha iniciado el manejo de operaciones frente a la fuente de información para ejecutar la operación solicitada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_TRANSACTION_IS_NOT_STARTED("El autocommit contra la fuente de información deseada se encuentra activado", "El autocommit requerido para llevar a cabo la operación contra la base de datos se encuentra activado."),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_STARTED("Error inesperado validando el estado de la operación deseada frente a la fuente de información", "Ocurrió un problema inesperado al validar si la operación solicitada contra la fuente de información deseada estaba iniciada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_TRANSACTION_IS_NOT_STARTED("Error SQL validando si la transacción no estaba iniciada", "Se presentó un error de tipo SQLException mientras se verificaba si la transacción en la conexión con la base de datos no había sido iniciada."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_CONNECTION_STATUS("Error SQL validando el estado de la conexión contra la base de datos", "Se presentó una excepción de tipo SQLException al intentar validar si la conexión contra la base de datos se encontraba activa o disponible."),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_NOT_STARTED( "Error inesperado validando si la transacción no estaba iniciada",  "Se presentó un problema inesperado al intentar validar si la transacción contra la base de datos no había sido iniciada. No fue una SQLException, sino un error no controlado en el proceso de validación."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_TRANSACTION_IS_STARTED("Error SQL validando si la transacción estaba iniciada", "Se presentó un error de tipo SQLException mientras se verificaba si la transacción en la conexión con la base de datos había sido iniciada."),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_STARTED( "Error inesperado validando si la transacción estaba iniciada",  "Se presentó un problema inesperado al intentar validar si la transacción contra la base de datos había sido iniciada. No fue una SQLException, sino un error no controlado en el proceso de validación."),
	TECHNICAL_ERROR_TRANSACTION_IS_STARTED("El autocommit contra la fuente de información deseada se encuentra desactivado", "El autocommit requerido para llevar a cabo la operación contra la base de datos se encuentra desactivado."),
	USER_ERROR_TRANSACTION_IS_STARTED("Manejo de operaciones frente a la fuente de información deseada ha sido iniciado", "Ya se encuentra iniciado el manejo de operaciones frente a la fuente de información para ejecutar la operación solicitada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_NOT_STARTED("Error inesperado tratando de validar el estado de la operacion deseada frente a la fuente de informacion se encontraba activado", "Ocurrió un problema inesperado al validar si la operación solicitada contra la fuente de información deseada estaba iniciada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	USER_ERROR_FACTORY_NOT_INITIALIZED("Factoria no iniciada", "La fuente de información sobre la cual se va a realizar la transacción seleccionada no esta disponible dentro del sistema. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_FACTORY_NOT_VALIDATED("Factotoria no validada", "La factoria de acceso a datos no existe y por tanto no se puede determinar a que fuente de datos debe conectarse."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error durante la consulta de la información de una categoría.", 
			"Se ha presentado un problema tratando de ejecutar la consulta de la información de una categoría, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la ejecución operación de consulta de la información de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de una categoría", 
			"Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia sql para llevar a cabo la operación de consulta de la información de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la preparación de la sentencia sql de la operación de consulta de la información de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error durante la consulta de la información de un cliente.",
			"Se ha presentado un problema tratando de ejecutar la consulta de la información de un cliente, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un cliente.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un cliente.", 
			"Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un cliente."),	
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un cliente.", 
			"Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un cliente. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error durante la consulta de la información de una mesa.","Se ha presentado un problema tratando de ejecutar la consulta de la información de una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error durante la consulta de la información de un empleado.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un empleado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un empleado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un empleado.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un empleado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un empleado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error durante la consulta de la información de un tipo de identificación.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un tipo de identificación, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tipo de identificación. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error durante la consulta de la información de un pedido.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un pedido.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error durante la consulta de la información de un pago.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un pago, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pago. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un pago.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un pago."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un pago.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un pago. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error durante la consulta de la información de un producto pedido.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un producto pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un producto pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un producto pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error durante la consulta de la información de un producto.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un producto, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un producto.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un producto.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un producto."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un producto.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un producto. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error durante la consulta de la información de un tamaño.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un tamaño, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tamaño. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error durante la consulta de la información de un estado.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un estado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un estado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un estado.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un estado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un estado.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un estado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error durante la consulta de la información de una mesa.","Se ha presentado un problema tratando de ejecutar la consulta de la información de una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un cliente.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un cliente."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un cliente mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un cliente mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un cliente mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un empleado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un empleado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un empleado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un pago.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un pago."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pago. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un producto pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un producto.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un producto."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un producto.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un estado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un estado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un estado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error durante el registro de una categoría.","Se ha presentado un problema tratando de ejecutar el registro de una categoría, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante el registro de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de registro de una categoría.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de registro de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de registro de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error durante la actualización de una categoría.","Se ha presentado un problema tratando de ejecutar la actualización de la información de una categoría, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la actualización de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de actualización de una categoría.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de actualización de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de una categoría. No fue una SQLException, sino un error no controlado en el proceso de actualización.");
	
	
	private String title;
	private String content;
	
	
	private MessagesEnum(final String title, final String content) {
		setTitle(title);
		setContent(content);
	}


	public String getTitle() {
		return title;
	}


	private void setTitle(final String title) {
		this.title = TextHelper.getDefaultWithTrim(title);
	}


	public String getContent() {
		return content;
	}


	private void setContent(final String content) {
		this.content = TextHelper.getDefaultWithTrim(content);
	}
	
	
	
	

}
