package co.edu.uco.rapizzas.crosscuting.messagescatalog;

import co.edu.uco.rapizzas.crosscuting.helper.TextHelper;

public enum MessagesEnum {
	
	USER_ERROR_SQL_CONNECTION_IS_EMPTY("Conexión contra la fuente de información deseada vacía", "La conexión requerida para llevar a cabo la operación contra la fuente de información deseada esta vacía. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_IS_EMPTY("Conexión contra la fuente de información deseada nula", "La conexión requerida para llevar a cabo la operación contra la base de datos llegó nula." ),
	USER_ERROR_SQL_CONNECTION_IS_CLOSED("Conexión contra la fuente de información deseada cerrada", "La conexión requerida para llevar a cabo la operación contra la fuente de información deseada esta cerrada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_IS_CLOSED("Conexión contra la fuente de información deseada cerrada", "La conexión requerida para llevar a cabo la operación contra la base de datos llegó cerrada." ),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_CONNECTION_STATUS("Problema inesperado validando el estado de la conexión contra la fuente de datos deseada ", "Se ha presentado un problema inesperado tratando de validar el estado de la conexión requerida para llevar a cabo la operación contra la fuente de información deseada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación"),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_CONNECTION_STATUS("Error inesperado validando si la conexión contra la base de datos estaba abierta", "Se presento un error de tipo SQLException al validar si la conexión contra base de datos estaba o no abierta." ),
	USER_ERROR_TRANSACTION_IS_NOT_STARTED("Manejo de operaciones frente a la fuente de información deseada no ha sido iniciado", "No se ha iniciado el manejo de operaciones frente a la fuente de información para ejecutar la operación solicitada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_TRANSACTION_IS_NOT_STARTED("El autocommit contra la fuente de información deseada se encuentra activado", "El autocommit requerido para llevar a cabo la operación contra la base de datos se encuentra activado."),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_STARTED("Error inesperado validando el estado de la operación deseada frente a la fuente de información", "Ocurrió un problema inesperado al validar si la operación solicitada contra la fuente de información deseada estaba iniciada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_TRANSACTION_IS_NOT_STARTED("Error SQL validando si la transacción no estaba iniciada", "Se presentó un error de tipo SQLException mientras se verificaba si la transacción en la conexión con la base de datos no había sido iniciada."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_CONNECTION_STATUS("Error SQL validando el estado de la conexión contra la base de datos", "Se presentó una excepción de tipo SQLException al intentar validar si la conexión contra la base de datos se encontraba activa o disponible."),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_NOT_STARTED( "Error inesperado validando si la transacción no estaba iniciada",  "Se presentó un problema inesperado al intentar validar si la transacción contra la base de datos no había sido iniciada. No fue una SQLException, sino un error no controlado en el proceso de validación."),
	TECHNICAL_ERROR_SQL_CONNECTION_SQL_EXCEPTION_VALIDATING_TRANSACTION_IS_STARTED("Error SQL validando si la transacción estaba iniciada", "Se presentó un error de tipo SQLException mientras se verificaba si la transacción en la conexión con la base de datos había sido iniciada."),
	TECHNICAL_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_STARTED( "Error inesperado validando si la transacción estaba iniciada",  "Se presentó un problema inesperado al intentar validar si la transacción contra la base de datos había sido iniciada. No fue una SQLException, sino un error no controlado en el proceso de validación."),
	TECHNICAL_ERROR_TRANSACTION_IS_STARTED("El autocommit contra la fuente de información deseada se encuentra desactivado", "El autocommit requerido para llevar a cabo la operación contra la base de datos se encuentra desactivado."),
	USER_ERROR_TRANSACTION_IS_STARTED("Manejo de operaciones frente a la fuente de información deseada ha sido iniciado", "Ya se encuentra iniciado el manejo de operaciones frente a la fuente de información para ejecutar la operación solicitada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	USER_ERROR_SQL_CONNECTION_UNEXPECTED_ERROR_VALIDATING_TRANSACTION_IS_NOT_STARTED("Error inesperado tratando de validar el estado de la operacion deseada frente a la fuente de informacion se encontraba activado", "Ocurrió un problema inesperado al validar si la operación solicitada contra la fuente de información deseada estaba iniciada. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	USER_ERROR_FACTORY_NOT_INITIALIZED("Factoria no iniciada", "La fuente de información sobre la cual se va a realizar la transacción seleccionada no esta disponible dentro del sistema. Por favor intente de nuevo y si el problema persiste, contacte al administrador de la aplicación."),
	TECHNICAL_ERROR_FACTORY_NOT_VALIDATED("Factotoria no validada", "La factoria de acceso a datos no existe y por tanto no se puede determinar a que fuente de datos debe conectarse."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error durante la consulta de la información de una categoría.", 
			"Se ha presentado un problema tratando de ejecutar la consulta de la información de una categoría, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la ejecución operación de consulta de la información de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de una categoría", 
			"Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia sql para llevar a cabo la operación de consulta de la información de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la preparación de la sentencia sql de la operación de consulta de la información de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error durante la consulta de la información de un cliente.",
			"Se ha presentado un problema tratando de ejecutar la consulta de la información de un cliente, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un cliente.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un cliente.", 
			"Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un cliente."),	
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un cliente.", 
			"Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un cliente. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error durante la consulta de la información de una mesa.","Se ha presentado un problema tratando de ejecutar la consulta de la información de una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_PREPARATION("Error SQL durante la  operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_PREPARATION("Error  inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de consulta."),
	USER_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error durante la consulta de la información de un empleado.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un empleado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un empleado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un empleado.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un empleado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un empleado. No fue una SQLException, sino un error no controlado en el proceso de consulta."),
	USER_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error durante la consulta de la información de un tipo de identificación.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un tipo de identificación, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tipo de identificación. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error durante la consulta de la información de un pedido.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un pedido.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un pedido. No fue una SQLException, sino un error no controlado en el proceso de consulta."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error durante la consulta de la información de un pago.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un pago, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pago. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un pago.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un pago."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un pago.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un pago. No fue una SQLException, sino un error no controlado en el proceso de consulta."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error durante la consulta de la información de un producto pedido.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un producto pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un producto pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un producto pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error durante la consulta de la información de un producto.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un producto, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un producto.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un producto.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un producto."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un producto.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un producto. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error durante la consulta de la información de un tamaño.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un tamaño, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tamaño. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error durante la consulta de la información de un estado.","Se ha presentado un problema tratando de ejecutar la consulta de la información de un estado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error inesperado durante la consulta de la información de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un estado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de un estado.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de un estado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de un estado.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de un estado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error durante la consulta de la información de una mesa.","Se ha presentado un problema tratando de ejecutar la consulta de la información de una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error inesperado durante la consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_PREPARATION("Error SQL durante la operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la preparación de la sentencia SQL para llevar a cabo la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_PREPARATION("Error inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la preparación de la sentencia SQL de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de una categoría.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un cliente.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un cliente."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un cliente mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un cliente mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un cliente mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un cliente mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un empleado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un empleado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un empleado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un tipo de identificación.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_ORDER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un pago.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un pago."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un pago. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un producto pedido."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un producto pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto pedido. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un producto.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un producto."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un producto.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un producto. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_SIZE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de un estado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de un estado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_STATUS_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de un estado. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	TECHNICAL_ERROR_SQL_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error SQL durante la operación de consulta de la información de una mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de consulta de la información de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_FINDING_TABLE_WHILE_EXECUTION("Error inesperado durante la operación de consulta de la información de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de consulta de la información de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error durante el registro de una categoría.","Se ha presentado un problema tratando de ejecutar el registro de una categoría, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante el registro de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de registro de una categoría.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de registro de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de registro de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una categoría. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error durante la actualización de una categoría.","Se ha presentado un problema tratando de ejecutar la actualización de la información de una categoría, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la actualización de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de una categoría. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error SQL durante la operación de actualización de una categoría.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de una categoría."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CATEGORY_WHILE_EXECUTION("Error inesperado durante la operación de actualización de una categoría.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de una categoría. No fue una SQLException, sino un error no controlado en el proceso de actualización."),
	USER_ERROR_SQL_EXCEPTION_CREATING_SIZE_WHILE_EXECUTION("Error durante el registro de un tamaño.","Se ha presentado un problema tratando de ejecutar el registro de un tamaño, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_SIZE_WHILE_EXECUTION("Error inesperado durante el registro de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de un tamaño. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_SIZE_WHILE_EXECUTION("Error SQL durante la operación de registro de un tamaño.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de registro de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_SIZE_WHILE_EXECUTION("Error inesperado durante la operación de registro de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_SIZE_WHILE_EXECUTION("Error durante la actualización de un tamaño.","Se ha presentado un problema tratando de ejecutar la actualización de la información de un tamaño, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_SIZE_WHILE_EXECUTION("Error inesperado durante la actualización de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un tamaño. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_SIZE_WHILE_EXECUTION("Error SQL durante la operación de actualización de un tamaño.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un tamaño."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_SIZE_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un tamaño.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un tamaño. No fue una SQLException, sino un error no controlado en el proceso de actualización."),
	USER_ERROR_SQL_EXCEPTION_CREATING_TABLE_WHILE_EXECUTION("Error durante el registro de una mesa.","Se ha presentado un problema tratando de ejecutar el registro de una mesa, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_TABLE_WHILE_EXECUTION("Error inesperado durante el registro de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_TABLE_WHILE_EXECUTION("Error SQL durante la operación de registro de una mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de registro de una mesa."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_TABLE_WHILE_EXECUTION("Error inesperado durante la operación de registro de una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de registro de una mesa. No fue una SQLException, sino un error no controlado en el proceso de registro."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_STATUS_WHILE_EXECUTION("Error durante la actualización de un estado.","Se ha presentado un problema tratando de ejecutar la actualización de la información de un estado, por favor intente de nuevo. Si el problema persiste, contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_STATUS_WHILE_EXECUTION("Error inesperado durante la actualización de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un estado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_STATUS_WHILE_EXECUTION("Error SQL durante la operación de actualización de un estado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un estado."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_STATUS_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un estado.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un estado. No fue una SQLException, sino un error no controlado en el proceso de actualización."),
	USER_ERROR_SQL_EXCEPTION_CREATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error durante la creación del tipo de identificación.", 
			"Se ha presentado un problema tratando de ejecutar la operación de creación del tipo de identificación, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la creación del tipo de identificación.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de creación del tipo de identificación. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error SQL durante la operación de creación del tipo de identificación.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la sentencia SQL para llevar a cabo la operación de creación del tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la operación de creación del tipo de identificación.", 
			"Se ha presentado un problema inesperado durante la ejecución de la sentencia SQL para llevar a cabo la operación de creación del tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error durante la actualización del tipo de identificación.", 
			"Se ha presentado un problema tratando de ejecutar la operación de actualización del tipo de identificación, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la actualización del tipo de identificación.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del tipo de identificación. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error SQL durante la operación de actualización del tipo de identificación.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la sentencia SQL para llevar a cabo la operación de actualización del tipo de identificación."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_IDENTIFICATIONTYPE_WHILE_EXECUTION("Error inesperado durante la operación de actualización del tipo de identificación.", 
			"Se ha presentado un problema inesperado durante la ejecución de la sentencia SQL para llevar a cabo la operación de actualización del tipo de identificación. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_PRODUCT_WHILE_EXECUTION("Error durante la creación del producto.", 
			"Se ha presentado un problema tratando de ejecutar la operación de creación del producto, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_PRODUCT_WHILE_EXECUTION("Error SQL durante la operación de creación del producto.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación del producto."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la creación del producto.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de creación del producto. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la operación de creación del producto.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de creación del producto. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_FINDING_PRODUCT_WHILE_PREPARATION("Error durante la preparación de la consulta de la información del producto.", 
			"Se ha presentado un problema durante la preparación de la operación de consulta de la información del producto."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_PRODUCT_WHILE_EXECUTION("Error durante la actualización del producto.", 
			"Se ha presentado un problema tratando de ejecutar la operación de actualización del producto, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_PRODUCT_WHILE_EXECUTION("Error SQL durante la operación de actualización del producto.", 
			"Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización del producto."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la actualización del producto.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del producto. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PRODUCT_WHILE_EXECUTION("Error inesperado durante la operación de actualización del producto.", 
			"Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del producto. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_CUSTOMER_WHILE_EXECUTION("Error durante la creación del cliente.","Se ha presentado un problema tratando de ejecutar la operación de creación del cliente, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_CUSTOMER_WHILE_EXECUTION("Error SQL durante la operación de creación del cliente.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación del cliente."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la creación del cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación del cliente. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la operación de creación del cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación del cliente. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_CUSTOMER_WHILE_EXECUTION("Error durante la actualización del cliente.","Se ha presentado un problema tratando de ejecutar la operación de actualización del cliente, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_CUSTOMER_WHILE_EXECUTION("Error SQL durante la operación de actualización del cliente.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización del cliente."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la actualización del cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del cliente. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CUSTOMER_WHILE_EXECUTION("Error inesperado durante la operación de actualización del cliente.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del cliente. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_EMPLOYEE_WHILE_EXECUTION("Error durante la creación del empleado.","Se ha presentado un problema tratando de ejecutar la operación de creación del empleado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_EMPLOYEE_WHILE_EXECUTION("Error SQL durante la operación de creación del empleado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación del empleado."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la creación del empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación del empleado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la operación de creación del empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación del empleado. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_EMPLOYEE_WHILE_EXECUTION("Error durante la actualización del empleado.","Se ha presentado un problema tratando de ejecutar la operación de actualización del empleado, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_EMPLOYEE_WHILE_EXECUTION("Error SQL durante la operación de actualización del empleado.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización del empleado."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la actualización del empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del empleado. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante la operación de actualización del empleado.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización del empleado. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_CUSTOMERTABLE_WHILE_EXECUTION("Error durante la creación de un cliente asignado a una mesa.","Se ha presentado un problema tratando de ejecutar la operación de creación de un cliente asignado a una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_CUSTOMERTABLE_WHILE_EXECUTION("Error SQL durante la operación de creación de un cliente asignado a una mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación de un cliente asignado a una mesa."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la creación de un cliente asignado a una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un cliente asignado a una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la operación de creación de un cliente asignado a una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un cliente asignado a una mesa. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_CUSTOMERTABLE_WHILE_EXECUTION("Error durante la actualización de un cliente asignado a una mesa.","Se ha presentado un problema tratando de ejecutar la operación de actualización de un cliente asignado a una mesa, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_CUSTOMERTABLE_WHILE_EXECUTION("Error SQL durante la operación de actualización de un cliente asignado a una mesa.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un cliente asignado a una mesa."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la actualización de un cliente asignado a una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un cliente asignado a una mesa. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_CUSTOMERTABLE_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un cliente asignado a una mesa.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un cliente asignado a una mesa. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_ORDER_WHILE_EXECUTION("Error durante la creación de un pedido.","Se ha presentado un problema tratando de ejecutar la operación de creación de un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_ORDER_WHILE_EXECUTION("Error SQL durante la operación de creación de un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación de un pedido."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_ORDER_WHILE_EXECUTION("Error inesperado durante la creación de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_ORDER_WHILE_EXECUTION("Error inesperado durante la operación de creación de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un pedido. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_ORDER_WHILE_EXECUTION("Error durante la actualización de un pedido.","Se ha presentado un problema tratando de ejecutar la operación de actualización de un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_ORDER_WHILE_EXECUTION("Error SQL durante la operación de actualización de un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un pedido."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_ORDER_WHILE_EXECUTION("Error inesperado durante la actualización de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_ORDER_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un pedido. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_PAYMENT_WHILE_EXECUTION("Error durante la creación de un pago.","Se ha presentado un problema tratando de ejecutar la operación de creación de un pago, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_PAYMENT_WHILE_EXECUTION("Error SQL durante la operación de creación de un pago.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación de un pago."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la creación de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un pago. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la operación de creación de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un pago. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_PAYMENT_WHILE_EXECUTION("Error durante la actualización de un pago.","Se ha presentado un problema tratando de ejecutar la operación de actualización de un pago, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_PAYMENT_WHILE_EXECUTION("Error SQL durante la operación de actualización de un pago.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un pago."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la actualización de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un pago. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PAYMENT_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un pago.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un pago. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_CREATING_PRODUCTORDER_WHILE_EXECUTION("Error durante la creación de un producto asignado a un pedido.","Se ha presentado un problema tratando de ejecutar la operación de creación de un producto asignado a un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_CREATING_PRODUCTORDER_WHILE_EXECUTION("Error SQL durante la operación de creación de un producto asignado a un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de creación de un producto asignado a un pedido."),
	USER_ERROR_UNEXPECTED_EXCEPTION_CREATING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la creación de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un producto asignado a un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_CREATING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la operación de creación de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de creación de un producto asignado a un pedido. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_UPDATING_PRODUCTORDER_WHILE_EXECUTION("Error durante la actualización de un producto asignado a un pedido.","Se ha presentado un problema tratando de ejecutar la operación de actualización de un producto asignado a un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_UPDATING_PRODUCTORDER_WHILE_EXECUTION("Error SQL durante la operación de actualización de un producto asignado a un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de actualización de un producto asignado a un pedido."),
	USER_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la actualización de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un producto asignado a un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_UPDATING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la operación de actualización de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de actualización de un producto asignado a un pedido. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	USER_ERROR_SQL_EXCEPTION_DELETING_PRODUCTORDER_WHILE_EXECUTION("Error durante la eliminación de un producto asignado a un pedido.","Se ha presentado un problema tratando de ejecutar la operación de eliminación de un producto asignado a un pedido, por favor intente de nuevo. Si el problema persiste por favor contacte al administrador del sistema."),
	TECHNICAL_ERROR_SQL_EXCEPTION_DELETING_PRODUCTORDER_WHILE_EXECUTION("Error SQL durante la operación de eliminación de un producto asignado a un pedido.","Se ha presentado un problema de tipo SQLException durante la ejecución de la operación de eliminación de un producto asignado a un pedido."),
	USER_ERROR_UNEXPECTED_EXCEPTION_DELETING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la eliminación de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de eliminación de un producto asignado a un pedido. Por favor intente de nuevo y si el problema persiste contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_DELETING_PRODUCTORDER_WHILE_EXECUTION("Error inesperado durante la operación de elimiación de un producto asignado a un pedido.","Se ha presentado un problema inesperado durante la ejecución de la operación de eliminación de un producto asignado a un pedido. No fue una SQLException, sino un error no controlado en el proceso de ejecución."),
	
	USER_ERROR_UNEXPECTED_EXCEPTION_REGISTERING_EMPLOYEE_WHILE_EXECUTION("Error inesperado durante el registro del empleado.",
		    "Se presentó un problema inesperado al intentar registrar la información del empleado. Por favor, intente nuevamente y si el problema persiste, contacte al administrador del sistema."),
	TECHNICAL_ERROR_UNEXPECTED_EXCEPTION_REGISTERING_EMPLOYEE_WHILE_EXECUTION("Excepción inesperada durante la operación de registro del empleado.",
		    "Ocurrió una excepción no controlada al ejecutar la operación de registro del empleado en la capa de negocio o de acceso a datos."),
	USER_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE("El valor  del campo es obligatorio.", "Se ha presentado un problema inesperado tratando de llevar  a cabo la operación deseada..."),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE("Error técnico ejecutando la regla IdValueIsNotDefaultValueRule.", "No se recibieron los parámetros requeridos para ejecutar la regla IdValueIsNotDefaultValueRule"),
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE_WITH_PARAMETERS("Error técnico ejecutando la regla IdValueIsNotDefaultValueRule.", "Se requerían dos parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla IdValueIsNotDefaultValueRule"),
	
	USER_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE_EMPTY_DATA("No  se pudo ejecutar la acción deseada.", "El siguiente dato es requerido para llevar a cabo la  operación: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE_EMPTY_DATA("La regla IdValueIsNotDefaultValueRule falló.", "La regla IdValueIsNotDefaultValueRule falló porque el identificador fue enviado como nulo"),
	
	USER_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE_DEFAULT_VALUE("No se pudo ejecutar la acción  deseada", "El identificador no puede tener el valor por defecto."),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_VALUE_IS_NOT_DEFAULT_VALUE_RULE_DEFAULT_VALUE("La regla IdValueIsNotDefaultValueRule falló.", "La regla IdValueIsNotDefaultValueRule falló porque el identificador tiene el valor por defecto (00000000-0000-0000-0000-000000000000)."),
	USER_ERROR_WHILE_EXECUTING_STRING_VALUE_IS_PRESENT_RULE("El valor  del campo es obligatorio.", "Se ha presentado un problema inesperado tratando de llevar a  cabo la operación deseada..."),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_TYPE_EXISTS_BY_ID("La regla IdentificationTypeExistsByIdRule falló.", "La regla IdentificationTypeExistsByIdRule falló porque el tipo de identificación se envió como vacío."),
	TECHNICAL_ERROR_WHILE_EXECUTING_ID_TYPE_EXISTS_BY_ID_WITH_PARAMETERS("Error técnico ejecutando la regla IdentificationTypeExistsByIdRule.", "Se requerían dos parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla IdentificationTypeExistsByIdRule"),
	
	USER_ERROR_IDENTIFICATION_TYPE_DOES_NOT_EXITS("El tipo de documento no existe", "El tipo de documento ingresado no existe"),
	TECHNICAL_ERROR_IDENTIFICATION_TYPE_DOES_NOT_EXITS("El tipo de documento no existe", "El tipo de documento con el siguiente id no existe: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_VALUE_IS_PRESENT_RULE("Error técnico ejecutando la regla StringValueIsPresentRule.", "No se recibieron los parámetros requeridos para ejecutar la regla StringValueIsPresentRule"),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_VALUE_IS_PRESENT_RULE_WITH_PARAMETERS("Error técnico ejecutando la regla StringValueIsPresentRule.", "Se requerían tres parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla StringValueIsPresentRule"),
	
	USER_ERROR_WHILE_EXECUTING_STRING_VALUE_IS_PRESENT_RULE_EMPTY_DATA("No se pudo  ejecutar la acción deseada.", "El siguiente dato es requerido para  llevar a cabo la operación: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_VALUE_IS_PRESENT_RULE_EMPTY_DATA("La regla StringValueIsPresentRule falló.", "Esto se debe a que el siguiente  dato es requerido para poder llevar a cabo la correcta ejecución de la operación:"),
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_LENGTH_VALUE_IS_VALID_RULE("Error técnico ejecutando la regla StringLengthValueIsValidRule.", "No se recibieron los parámetros requeridos para ejecutar la regla StringLengthValueIsPresentRule"),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_LENGTH_VALUE_IS_VALID_RULE_WITH_PARAMETERS("Error técnico ejecutando la regla StringLengthValueIsValidRule.", "Se requerían cinco parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla StringLengthValueIsValidRule"),
	
	USER_ERROR_WHILE_EXECUTING_STRING_LENGTH_VALUE_IS_VALID_RULE("No se  pudo ejecutar la acción deseada.", "El siguiente dato debe tener una longitud entre (min, max): "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_LENGTH_VALUE_IS_VALID_RULE_WITH_LENGTH("La regla StringLengthValueIsPresentRule falló.","Esto se debe a que el siguiente dato no tiene una longitus esperada entre (min, max): "),
	USER_ERROR_WHILE_EXECUTING_UUID_VALUE_IS_PRESENT_RULE("El valor del campo es obligatorio.", "Se ha presentado un problema inesperado tratando de llevar a cabo la operación deseada..."),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_UUID_VALUE_IS_PRESENT_RULE("Error técnico ejecutando la regla UUIDValueIsPresentRule.", "No se recibieron los parámetros requeridos para ejecutar la regla UUIDValueIsPresentRule"),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_UUID_VALUE_IS_PRESENT_RULE_WITH_PARAMETERS("Error técnico ejecutando la regla UUIDValueIsPresentRule.", "Se requerían tres parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla UUIDValueIsPresentRule"),
	
	USER_ERROR_WHILE_EXECUTING_UUID_VALUE_IS_PRESENT_RULE_EMPTY_DATA("No se pudo  ejecutar la acción deseada.", "El siguiente dato es requerido para llevar a cabo la operación: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_UUID_VALUE_IS_PRESENT_RULE_EMPTY_DATA("La regla UUIDValueIsPresentRule falló.", "Esto se debe a que el siguiente dato es requerido para poder llevar a cabo la correcta ejecución de la operación:"),
	
	SUCCESFULLY_EMPLOYEE_REGISTERED("Empleado registrado con éxito", "El registro del empleado se llevó a cabo con éxito"),
	
	UNEXPECTED_ERROR_WHILE_REGISTERING_EMPLOYEE("Error inesperado durante el registro del empleado", "Se presentó un error inesperado llevando a cabo el registro del empleado, si el error persiste, por favor contacte con el administrador"),
	
	TECHNICAL_ERROR_VALUE_EMPLOYEEE_DOES_NOT_EXISTS_BY_MOBILE_NUMBER("Error tratando de llevar  a cabo la  operación", "No se recibieron los parametros requeridos para ejecutar la regla EmployeeDoesNotExistsWithSamePhoneNumberRule"),
	TECHNICAL_ERROR_WRONG_EMPLOYEE_LENGTH_VALUE_EMPLOYEE_DOES_NOT_EXISTS_BY_MOBILE_NUMBER("No fueron  ingresados todos los parametros", "Se requerían dos parametros y llegó una cantidad menor a esta requeridos para ejecutar la regla EmployeeDoesNotExistsWithSamePhoneNumberRule"),
	USER_ERROR_EMPLOYEE_DOES_EXISTS_BY_MOBILE_NUMBER("Ya hay un empleado registrado con ese número de teléfono", "No es posible llevar a cabo la operación, ya que ya existe un empleado con el mismo  número de teléfono"),
	TECHNICAL_ERROR_EMPLOYEE_DOES_EXISTS_BY_MOBILE_NUMBER("Ya hay un empleado registrado con ese  número de teléfono", "No es posible llevar a cabo la operación, ya que ya existe un empleado dentro de la fuente de datos con el mismo  número de teléfono"),
	
	TECHNICAL_ERROR_VALUE_IS_NOT_PRESENT_EMPLOYEE("Error tratando de llevar a cabo la  operación", "No se recibieron los parametros requeridos para ejecutar la regla EmployeeExistsByIdRule"),
	TECHNICAL_ERROR_WRONG_EMPLOYEE_LENGTH_VALUE("No fueron  ingresados todos los parametros", "Se requerían dos parametros y llegó una cantidad menor a esta requeridos para ejecutar la regla EmployeeExistsByIdRule"),
	USER_ERROR_EMPLOYEE_DOES_NOT_EXITS("El empleado no existe", "El empleado ingresada no existe"),
	TECHNICAL_ERROR_EMPLOYEE_DOES_NOT_EXITS("El empleado no existe", "El empleado con el siguiente id no existe: "),
	
	TECHNICAL_ERROR_VALUE_EMPLOYEE_DOES_NOT_EXISTS_BY_IDENTIFICATION("Error tratando de llevar a cabo la operación", "No se recibieron los parametros requeridos para ejecutar la regla EmployeeDoesNotExistsWithSameIdtypeAndNumberRule"),
	TECHNICAL_ERROR_WRONG_EMPLOYEE_LENGTH_VALUE_EMPLOYEE_DOES_NOT_EXISTS_BY_IDENTIFICATION("No fueron ingresados todos los parametros", "Se requerían tres parametros y llegó una cantidad menor a esta requeridos para ejecutar la regla EmployeeDoesNotExistsWithSameIdtypeAndNumberRule"),
	USER_ERROR_EMPLOYEE_DOES_EXISTS_BY_IDENTIFICATION("Ya hay un empleado registrado con ese tipo y número de identificación", "No es posible llevar a cabo la operación, ya que ya existe un empleado con el mismo tipo y número de identificación"),
	TECHNICAL_ERROR_EMPLOYEE_DOES_EXISTS_BY_IDENTIFICATION("Ya hay un empleado registrado con ese tipo y número de identificación", "No es posible llevar a cabo la operación, ya que ya existe un empleado dentro de la fuente de datos con el mismo tipo y número de identificación "),
	
	TECHNICAL_ERROR_VALUE_EMPLOYEE_IS_NOT_PRESENT("Error tratando de llevar a cabo la operación", "No se recibieron los parametros requeridos para ejecutar el validator ValidateDataEmployeeConsistencyForRegisterNewInformation"),
	TECHNICAL_ERROR_WRONG_EMPLOYEE_LENGTH_VALUE_IS_NOT_PRESENT("No fueron ingresados todos los parametros", "Se requería un solo parametro y llegó una cantidad menor a esta requerida para ejecutar el validator ValidateDataEmployeeConsistencyForRegisterNewInformation"),
	USER_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE("El valor del campo es obligatorio.", "Se ha presentado un problema inesperado tratando de llevar a cabo la operación deseada..."),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE("Error técnico ejecutando la regla StringFormatValueIsValidRule.", "No se recibieron los parámetros requeridos para ejecutar la regla StringFormatValueIsValidRule"),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE_WITH_PARAMETERS("Error técnico ejecutando la regla StringFormatValueIsValidRule.", "Se requerían cuatro parámetros y llegó una cantidad menor a esta requeridos para ejecutar la regla StringFormatValueIsValidRule"),
	
	USER_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE_EMPTY_DATA("No se pudo ejecutar la acción deseada.", "El siguiente dato es requerido para llevar a cabo la operación: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE_EMPTY_DATA("La regla StringFormatValueIsValidRule falló.", "Esto se debe a que el siguiente dato es requerido para poder llevar a cabo la correcta ejecución de la operación:"),
	
	USER_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE_INVALID_FORMAT("No se pudo ejecutar la acción deseada.", "El formato del siguiente dato no es válido: "),
	
	TECHNICAL_ERROR_WHILE_EXECUTING_STRING_FORMAT_VALUE_IS_VALID_RULE_INVALID_FORMAT("La regla StringFormatValueIsValidRule falló.", "La regla StringFormatValueIsValidRule falló porque el siguiente dato no cumple con el patrón esperado: ");

	
	private String title;
	private String content;
	
	
	private MessagesEnum(final String title, final String content) {
		setTitle(title);
		setContent(content);
	}


	public String getTitle() {
		return title;
	}


	private void setTitle(final String title) {
		this.title = TextHelper.getDefaultWithTrim(title);
	}


	public String getContent() {
		return content;
	}


	private void setContent(final String content) {
		this.content = TextHelper.getDefaultWithTrim(content);
	}

}
